// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIqsaw2ygDtTHAn2T_zNnnn0N4qpPmNjc',
    appId: '1:192573976334:web:e3448507be04187a0ef15f',
    messagingSenderId: '192573976334',
    projectId: 'flutterfirebasepushmessage',
    authDomain: 'flutterfirebasepushmessage.firebaseapp.com',
    storageBucket: 'flutterfirebasepushmessage.appspot.com',
    measurementId: 'G-1CQ7PS1FKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRR5OIsNay4aEqw--tRb1qKSvl1I93nZI',
    appId: '1:192573976334:android:0c708c60cbf934480ef15f',
    messagingSenderId: '192573976334',
    projectId: 'flutterfirebasepushmessage',
    storageBucket: 'flutterfirebasepushmessage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKrtYbbjCj5w1mKI_bkgt0gipMmzgvko',
    appId: '1:192573976334:ios:9a4d21c47565324d0ef15f',
    messagingSenderId: '192573976334',
    projectId: 'flutterfirebasepushmessage',
    storageBucket: 'flutterfirebasepushmessage.appspot.com',
    iosBundleId: 'com.example.flutterFirebasePushMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLKrtYbbjCj5w1mKI_bkgt0gipMmzgvko',
    appId: '1:192573976334:ios:22f352cf73632d380ef15f',
    messagingSenderId: '192573976334',
    projectId: 'flutterfirebasepushmessage',
    storageBucket: 'flutterfirebasepushmessage.appspot.com',
    iosBundleId: 'com.example.flutterFirebasePushMessage.RunnerTests',
  );
}
